base/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^single/(?P<post_id>\d+)/$', views.single, name='single'),
]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('base.urls', namespace='base')),
    url(r'^admin/', admin.site.urls),
]

base/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from ckeditor import fields


class Tag(models.Model):
    name = models.CharField('Name', max_length=50)

    def __str__(self):
        return self.name


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Entwurf'),
        ('publish', 'Veröffentlicht'),
        ('trash', 'Gelöscht')
    )

    title = models.CharField('Titel', max_length=255)
    content = fields.RichTextField('Inhalt')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='posts')
    publish = models.DateTimeField('Veröffentlichungs-Datum', default=timezone.now)
    status = models.CharField('Status', choices=STATUS_CHOICES, max_length=10)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title


class Comment(models.Model):
    email = models.EmailField('Email')
    homepage = models.URLField('Homepage', blank=True, null=True)
    text = models.TextField('Text')
    post = models.ForeignKey(Post, related_name='comments')
    date = models.DateTimeField('Datum', default=timezone.now, editable=False)

base/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('email', 'homepage', 'text')

base/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from django.utils import timezone
from .forms import CommentForm


def index(request):
    posts = Post.objects.filter(status='publish').order_by('-publish')

    posts = posts.select_related('user').filter(publish__lte=timezone.now())

    context = {
        'posts': posts
    }

    return render(request, "base/index.html", context)


def single(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='publish', publish__lte=timezone.now())
    form = CommentForm()

    if request.method == 'POST':
        form = CommentForm(request.POST)
        form.instance.post_id = post_id

        if form.is_valid():
            form.save()
            return redirect('base:single', post_id=post_id)

    context = {
        'post': post,
        'form': form
    }

    return render(request, "base/single.html", context)

base/templates/base/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Welcome!{% endblock %} - Der Blog</title>
    <link rel="stylesheet" href="{% static "base/style.css" %}" />
</head>
<body>
<div class="container">
    {% block content %}{% endblock %}
</div>
</body>
</html>

base/templates/base/index.html
{% extends "base/base.html" %}

{% block title %}Übersicht{% endblock %}

{% block content %}
<h2>Übersicht</h2>

<ul>

{% for post in posts %}
    <li><a href="{% url "base:single" post.id %}">{{ post.title }}</a> von {{ post.user }} ({{ post.publish|date:"d.m.Y H:i:s" }})</li>
{% endfor %}
</ul>
    {{ posts }}
{% endblock %}

base/templates/base/single.html
{% extends "base/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<a href="{% url "base:index" %}">Zurück</a>
<h2>{{ post.title }}</h2>
<p>{{ post.user.username }}</p>
<p>{{ post.content|safe }}</p>
<br /><br />
<form method="post" action="#">
    {% csrf_token %}
<table>
    {{ form.as_table }}

</table>
<input type="submit" value="Abschicken" />
</form>

<br /><br />
    <h2>Kommentare</h2>

    <ul>
    {% for comment in post.comments.all %}
        <p>{{ comment.email }} {{ comment.homepage|default:"NA" }}</p>
        <p>{{ comment.text }}</p>
    {% empty %}
        <p>Keine Kommentare vorhanden.</p>
    {% endfor %}
    </ul>
{% endblock %}